# Generated by Django 4.0 on 2021-12-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ideafinalhist',
            fields=[
                ('savedtime', models.DateTimeField()),
                ('ideanum', models.IntegerField(primary_key=True, serialize=False)),
                ('myidea', models.CharField(default=None, max_length=255)),
                ('importance', models.CharField(default=None, max_length=250)),
                ('theoryofchange', models.CharField(default=None, max_length=250)),
                ('outcomealign', models.CharField(default=None, max_length=250)),
                ('researchplan', models.CharField(default=None, max_length=250)),
                ('partnership', models.TextField()),
                ('lack', models.TextField()),
                ('implement', models.TextField()),
                ('outcomedetail', models.CharField(default=None, max_length=250)),
                ('impact', models.CharField(default=None, max_length=250)),
                ('definesuccess', models.CharField(default=None, max_length=250)),
                ('other', models.TextField()),
                ('budget_TF', models.SmallIntegerField(default=None)),
                ('budgetnar_TF', models.SmallIntegerField(default=None)),
                ('workplan_TF', models.SmallIntegerField(default=None)),
            ],
        ),
    ]
